name: Docker_xjh

on:
  workflow_dispatch:
  #push:
  #  branches: [ develop ]
  schedule:
    - cron: '0 2,8,14,20 * * *'

jobs:

  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
    - name: Before freeing up disk space
      run: |
        echo "Before freeing up disk space"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    # 增加可用磁盘空间
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:

        root-reserve-mb: 2048
        swap-size-mb: 128
        remove-dotnet: 'true'
        remove-haskell: 'true'
        # 如果空间还是不够用，可以把以下开启，清理出更多空间
        # remove-android: 'true'
        # remove-codeql: 'true'
        build-mount-path: '/var/lib/docker/'

    - name: Restart docker
      run: sudo service docker restart

    - name: Free up disk space complete
      run: |
        echo "Free up disk space complete"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and pull image 
      run: |
        timeFirst=$(date +%s)
        timeLast=$timeFirst
        echoTime() {
            timeNext=$(date +%s)
            echo "$1 过程耗时：$[($timeNext-$timeLast)/60]分$[($timeNext-$timeLast)%60]秒，累计耗时：$[($timeNext-$timeFirst)/60]分$[($timeNext-$timeFirst)%60]秒。    " `date`
            timeLast=$timeNext
        }
        echo "=============================================================================="
        docker images
        echo "------------------------------------------------------------------------------"
        df -hT
        echo "=============================================================================="
                
        docker pull --platform=amd64 xijiahui/oracle_database:19.3.0-ee
        docker rmi  xijiahui/oracle_database:19.3.0-ee
        echoTime "oracle_database:19.3.0-ee_x64"
        echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
        
        docker pull --platform=arm64 xijiahui/oracle_database:19.3.0-ee
        docker rmi  xijiahui/oracle_database:19.3.0-ee
        echoTime "oracle_database:19.3.0-ee_arm64"
        echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
       
        docker pull xijiahui/oracle_database:12.1.0.2-ee
        docker rmi  xijiahui/oracle_database:12.1.0.2-ee
        echoTime "oracle_database:12.1.0.2-ee"
        echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
        
        docker pull xijiahui/oracle_database:12.2.0.1-ee
        docker rmi  xijiahui/oracle_database:12.2.0.1-ee
        echoTime "oracle_database:12.2.0.1-ee"
        echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
        
        docker pull xijiahui/oracle_database:18.3.0-ee
        docker rmi  xijiahui/oracle_database:18.3.0-ee
        echoTime "oracle_database:18.3.0-ee"
        echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
        
        docker pull xijiahui/oracle_database:11.2.0.4-ee
        docker rmi  xijiahui/oracle_database:11.2.0.4-ee
        echoTime "oracle_database:11.2.0.4-ee"
        echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"

        docker pull xijiahui/adminer:4.8.1-oracle
        docker rmi  xijiahui/adminer:4.8.1-oracle
        docker pull xijiahui/adminer:4.17.1-oracle
        docker rmi  xijiahui/adminer:4.17.1-oracle
        docker pull xijiahui/adminer:5.1.0-oracle
        docker rmi  xijiahui/adminer:5.1.0-oracle
        docker pull xijiahui/adminer:5.2.1-oracle
        docker rmi  xijiahui/adminer:5.2.1-oracle
        echoTime "xijiahui/adminer"
        echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"

        echo "=============================================================================="
        docker images
        echo "------------------------------------------------------------------------------"
        df -hT
        echo "=============================================================================="
        
